# @package _group_
common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  no_epoch_checkpoints: true
  save_dir: checkpoints

task:
  _name: masked_lm
  data: ???
  sample_break_mode: complete
  tokens_per_sample: 2048

criterion: masked_lm

dataset:
  batch_size: 8
  ignore_unused_valid_subsets: true

optimizer:
  _name: adam
  weight_decay: 0.01
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 5000

optimization:
  clip_norm: 0
  lr: [0.0003]
  max_update: 125000
  update_freq: [4]

model:
  _name: roberta
  max_positions: 2048
  dropout: 0.1
  attention_dropout: 0.1
  encoder_self_attention_type: mha
